---
image: python:3.7

before_script:
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install pylint flake8

stages:
  - linting

flake8:
  stage: linting
  script:
    - flake8 redfish_api_toolkit/

pylint:
  stage: linting
  script:
    - pylint redfish_api_toolkit/
